### ISSUE TITLE
Deployment automation

### ISSUE THREAD

**Issue by ryan0x44** [NetoECommerce/Skeletal#108]
Hi there,

I managed to find a way to streamline my SFTP deployments with Neto theme development workflow, without using a fancy SFTP client like Tranmit. Hopefully someone finds this useful, and maybe this could even be mentioned somewhere on the advanced docs.

Setup:
1. Unzip the Skeletal theme and initialise your git repo with `git init`
2. Install [dploy](https://github.com/LeanMeanFightingMachine/dploy) with `npm install dploy -g`
3. Create post-commit git hook with `echo -e '#!/bin/sh\ndploy' > .git/hooks/post-commit`
4. Ensure the post-commit git hook will run with `chmod +x .git/hooks/post-commit`
5. Create a `dploy.yaml` file with the below template:

```
neto:
    scheme: sftp
    host: [YOUR-DETAILS].neto.com.au
    port: 2022
    user: [YOUR-DETAILS]
    pass: 
    check: false
    path:
        local:
        remote:
    exclude:
        ["dploy.yaml", ".gitignore"]
    include:
        "httpdocs/*": "httpdocs/"
        "private/*": "private/"
```

_Note: if you specify a value for 'pass', make sure dploy.yaml is in your .gitignore file. Otherwise you can just leave this value blank and it will ask for your password each time._

With this set up, every time you commit, your changed files will be deployed! :) e.g.

![screen shot 2016-02-11 at 4 12 28 pm](https://cloud.githubusercontent.com/assets/1902353/12969826/5835d762-d0da-11e5-8890-84d5a873aa59.png)

Cheers,
Ryan
